"""empty message

Revision ID: 00f78e518654
Revises: 6bffb0f57ec0
Create Date: 2020-12-02 08:51:17.220684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f78e518654'
down_revision = '6bffb0f57ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_name', sa.String(), nullable=False))
    op.drop_column('books', 'publisher_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books', 'book_name')
    # ### end Alembic commands ###
